routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FrontendController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('index');

Route::get('/post/{category}.html', [FrontendController::class, 'postIndex'])->name('postIndex');
Route::get('/post/{post}/{slug}.html', [FrontendController::class, 'postDetail'])->name('postDetail');

Route::get('/page/{page}/{slug}.html', [FrontendController::class, 'pageDetail'])->name('pageDetail');

Route::get('/events.html', [FrontendController::class, 'eventIndex'])->name('eventIndex');
Route::get('/event/{event}/{slug}.html', [FrontendController::class, 'eventDetail'])->name('eventDetail');

Route::get('/galleries.html', [FrontendController::class, 'galleryIndex'])->name('galleryIndex');
Route::get('/gallery/{gallery}/{slug}.html', [FrontendController::class, 'galleryDetail'])->name('galleryDetail');

Route::get('/download/{category}.html', [FrontendController::class, 'downloadIndex'])->name('downloadIndex');

Route::get('/call-for-paper.html', [FrontendController::class, 'callForPaper'])->name('callForPaper');
Route::post('/call-for-paper-store', [FrontendController::class, 'callForPaperPost'])->name('callForPaperPost');

app/Models/Event.php
<?php

namespace App\Models;

use Carbon\Carbon;
use \DateTimeInterface;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Event extends Model implements HasMedia
{
    use InteractsWithMedia;
    use HasFactory;

    public $table = 'events';

    protected $appends = [
        'banner',
    ];

    protected $dates = [
        'start_at',
        'end_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'start_at',
        'end_at',
        'description',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function getSlugAttribute()
    {
        $name = Str::limit($this->name, 50, '');
        return Str::slug($name);
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
        $this->addMediaConversion('flayer')->fit('crop', 991, 640);
    }

    public function getBannerAttribute()
    {
        $file = $this->getMedia('banner')->last();
        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->preview   = $file->getUrl('preview');
            $file->preview   = $file->getUrl('flayer');
        }

        return $file;
    }

    public function getBannerImageAttribute()
    {
        $file = $this->getMedia()->last();
        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->preview   = $file->getUrl('preview');
            $file->preview   = $file->getUrl('flayer');
        }

        return $file;
    }
}

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\CallForPaper;
use App\Models\Page;
use App\Models\Post;
use App\Models\Event;
use App\Models\Gallery;
use App\Models\Category;
use App\Models\Download;
use App\Models\Registration;
use Illuminate\Http\Request;
use App\Settings\InformationMemberSettings;

class FrontendController extends Controller
{
    public function index()
    {
        $posts = Post::query()
            ->with('visits')
            ->whereNotNUll('published_at')
            ->where('category_id', 1)
            ->where('is_slider', false)
            ->orderBy('published_at', 'desc')
            ->limit(3)
            ->get();

        $sliders = Post::query()
            ->with('visits')
            ->whereNotNUll('published_at')
            ->where('is_slider', true)
            ->orderBy('published_at', 'desc')
            ->limit(3)
            ->get();

        $callForPaper = CallForPaper::latest()->first();

        return view('frontend.index', compact('posts', 'sliders', 'callForPaper'));
    }

    public function postIndex($category)
    {
        $cat = str_replace("-", " ", $category);
        $category = Category::where('name', $cat)->firstOrFail();

        $posts = Post::query()
            ->with('visits')
            ->whereNotNUll('published_at')
            ->where('category_id', $category->id)
            ->orderBy('published_at', 'desc')
            ->paginate(9);

        return view('frontend.posts.index', compact('posts', 'cat'));
    }

    public function postDetail(Post $post)
    {
        $newPosts = Post::query()
            ->with('visits')
            ->whereNotNUll('published_at')
            ->orderBy('published_at', 'desc')
            ->limit(4)
            ->get();

        $popularPosts = visits('App\Models\Post')->top(4);

        $post->vzt()->increment();

        return view('frontend.posts.detail', compact('newPosts', 'popularPosts', 'post'));
    }

    public function pageDetail(Page $page)
    {
        return view('frontend.pages.detail', compact('page'));
    }

    public function downloadIndex($category)
    {
        $cat = str_replace("-", " ", $category);
        $downloads = Download::where('category', $cat)->latest()->get();

        return view('frontend.downloads.index', compact('downloads', 'cat'));
    }

    public function galleryIndex()
    {
        $galleries = Gallery::latest()->paginate(9);

        return view('frontend.galleries.index', compact('galleries'));
    }

    public function galleryDetail(Gallery $gallery)
    {
        return view('frontend.galleries.detail', compact('gallery'));
    }

    public function eventIndex()
    {
        $events = Event::latest()->paginate(8);

        return view('frontend.events.index', compact('events'));
    }

    public function eventDetail(Event $event)
    {
        return view('frontend.events.detail', compact('event'));
    }

    public function callForPaper()
    {
        $callForPaper = CallForPaper::latest()->first();

        return view('frontend.callForPapers.index', compact('callForPaper'));
    }

    public function callForPaperPost(Request $request)
    {
        Registration::create($request->all());
        session()->flash('message', 'Berhasil terkirim');
        return back();
    }
}

resources/views/frontend/events/detail.blade.php
@extends('frontend.layouts.app')

@section('title')
{{ $event->name ?? '-' }}
@endsection

@section('content')
<!-- ============================================================== -->
<!-- Static Slider 10  -->
<!-- ============================================================== -->
<div class="banner-innerpage" style="background-image:url(/assets/images/innerpage/banner-bg2.jpg)">
    <div class="container">
        <!-- Row  -->
        <div class="row justify-content-center ">
            <!-- Column -->
            <div class="text-center col-md-8 align-self-center" data-aos="fade-down" data-aos-duration="1200">
                <h1 class="title">{{ $event->name ?? '-' }}</h1>
            </div>
            <!-- Column -->
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Static Slider 10  -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Blog example  -->
<!-- ============================================================== -->
<div class="spacer">
    <div class="container">
        <!-- Row  -->
        <div class="row justify-content-center">
            <div class="col-md-8 wrap-feature2-box">
                <div class="card card-shadow hover1" style="border-radius: 20px">
                    @if($event->banner_image)
                        <a href="{{ $event->banner_image->getUrl() }}" target="_blank" style="display: inline-block">
                            <img class="card-img-top" src="{{ $event->banner_image->getUrl() }}" style="border-radius: 20px;">
                        </a>
                    @else
                        <img class="card-img-top" src="/img/default/agenda.jpg" alt="banner" style="border-radius: 20px;" />
                    @endif
                    <div class="card-body">
                        <h3 class="font-medium text-center">{{ $event->name ?? '' }}</h3>
                        <div class="row">
                            <div class="text-center col-md-6 b-r">
                                <dl class="m-t-20">
                                    <dt>Tanggal Mulai</dt>
                                    <dd>{{ $event->start_at ? Date::parse($event->start_at)->format('l, d M Y') : '' ?? '' }}</dd>
                                </dl>
                            </div>
                            <div class="text-center col-md-6">
                                <dl class="m-t-20">
                                    <dt>Tanggal Selesai</dt>
                                    <dd>{{ $event->start_at ? Date::parse($event->end_at)->format('l, d M Y') : '' ?? '' }}</dd>
                                </dl>
                            </div>
                            <div class="col-md-12 m-t-20" style="text-align: justify;">
                                <span class="font-medium">Keterangan:</span> <br>
                                {!! $event->description ?? '' !!}
                            </div>
                            <div class="text-center col-md-12 m-t-20">
                                @if($event->banner_image)
                                <a href="{{ $event->banner_image->getUrl() }}" target="_blank" class="btn btn-danger btn-rounded"><i class="fa fa-download"></i> Unduh Flayer</a>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Row  -->
    </div>
</div>
<!-- ============================================================== -->
<!-- End Blog example -->
<!-- ============================================================== -->
@endsection

@section('styles')
<style>
    .attachment__caption {
        display: none;
    }
</style>
@endsection

@section('scripts')
<script type="text/javascript">
    $("document").ready(function() {
        $("img").addClass("img-responsive");
    });
</script>
@endsection

resources/views/frontend/events/index.blade.php
@extends('frontend.layouts.app')

@section('title')
    Event PSKP
@endsection

@section('content')
<!-- ============================================================== -->
<!-- Static Slider 10  -->
<!-- ============================================================== -->
<div class="banner-innerpage" style="background-image:url(/assets/images/innerpage/banner-bg2.jpg)">
    <div class="container">
        <!-- Row  -->
        <div class="row justify-content-center ">
            <!-- Column -->
            <div class="col-md-8 align-self-center text-center" data-aos="fade-down" data-aos-duration="1200">
                <h1 class="title">Event PSKP</h1>
                <h6 class="subtitle op-8">Berikut daftar event terbaru dari kegiatan yang akan dilaksanakan oleh PSKP FK Unizar.</h6>
            </div>
            <!-- Column -->
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Static Slider 10  -->
<!-- ============================================================== -->
<div class="spacer feature2 bg-light">
    <div class="container">
        <!-- Row  -->
        <div class="row m-t-40">
            <!-- Column -->
            @foreach ($events as $event)
            <div class="col-md-3 wrap-feature2-box">
                <div class="card card-shadow hover1" style="border-radius: 20px">
                    @if($event->banner_image)
                        <a href="{{ $event->banner_image->getUrl() }}" target="_blank" style="display: inline-block">
                            <img class="card-img-top" src="{{ $event->banner_image->getUrl() }}" style="border-radius: 20px;">
                        </a>
                    @else
                        <img class="card-img-top" src="/img/default/agenda.jpg" alt="banner" style="border-radius: 20px;" />
                    @endif
                    <div class="card-body">
                        <h5 class="font-medium text-center">{{ $event->name ?? '' }}</h5>
                        <div class="row">
                            <div class="text-center col-md-6 b-r">
                                <dl class="m-t-20">
                                    <dt>Tanggal Mulai</dt>
                                    <dd>{{ $event->start_at ? Date::parse($event->start_at)->format('l, d M Y') : '' ?? '' }}</dd>
                                </dl>
                            </div>
                            <div class="text-center col-md-6">
                                <dl class="m-t-20">
                                    <dt>Tanggal Selesai</dt>
                                    <dd>{{ $event->start_at ? Date::parse($event->end_at)->format('l, d M Y') : '' ?? '' }}</dd>
                                </dl>
                            </div>
                            <div class="col-md-12 m-t-20" style="text-align: justify;">
                                <span class="font-medium">Keterangan:</span> <br>
                                {!! strip_tags(Str::limit($event->description, 100)) !!}
                            </div>
                            <div class="text-center col-md-12 m-t-20">
                                @if($event->banner_image)
                                <a href="{{ $event->banner_image->getUrl() }}" target="_blank" class="btn btn-danger btn-rounded btn-sm"><i class="fa fa-download"></i></a>
                                @endif
                                <a href="{{ route('eventDetail', [$event->id, $event->slug]) }}" target="_blank" class="btn btn-info btn-rounded btn-sm"> Selengkapnya</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
        <div class="col-md-12">
            <div class="text-center">
                {{ $events->links() }}
            </div>
        </div>
    </div>
</div>


@endsection

@section('styles')
@endsection

@section('scripts')
@endsection